### ISSUE TITLE
X-Touch One support

### ISSUE THREAD

**Issue by MatteAce** [Shuptuu/TheLink#1]
Hi, does this supports or will ever support in the future the connection to an X-Touch One?

**Comment by sloun68** [comment]
I do not know

**Comment by sloun68** [comment]
I donated through Pai Pal, my email is listed on it

**Comment by Shuptuu** [comment]
> Hi, does this supports or will ever support in the future the connection to an X-Touch One?

I'm afraid not. It's only for the X-Touch mini.
